# Generated by Django 5.2.15 on 2026-07-05 12:30

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_cover_image_url_book_cover_image'),
        ('shelves', '0002_usershelf_reviewed_at_reviewcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershelf',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='usershelf',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='shelf_rating_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='usershelf',
            constraint=models.CheckConstraint(condition=models.Q(('shelf_type', 'read'), models.Q(('rating__isnull', True), ('reviewed_at__isnull', True)), _connector='OR'), name='review_data_only_when_read'),
        ),
    ]
